name: 'Due Dates'
description: 'Add due dates to issues'
author: 'Patrick Sinco'
inputs:
  GH_TOKEN:
    description: GitHub token used to make API requests
    required: true
runs:
  using: 'node12'
  main: 'index.js'
